Repository torch-ai/crunchbase-js, pull requests merged in 2022-03, with the labels that each got.

#20 Funding rounds search
  README.md
  src/components/search/Search.test.ts
  src/components/search/Search.ts
Labels: documentation, enhancement

#22 Add supported collection_ids to the autocomplete endpoint
  src/components/autocomplete/Autocomplete.types.ts
Labels: enhancement

#23 Bug/collections endpoint commas
  src/components/autocomplete/Autocomplete.test.ts
  src/components/autocomplete/Autocomplete.ts
  src/components/autocomplete/Autocomplete.types.ts
Labels: bug
